Add files via upload
jt-class/TheEndOfButterfly pull request #4
Opened 2024-08-19 14:49 UTC by Lanciee

Document containing the flow of the story

2024-08-20 04:51 UTC, jtinosa requested changes
Pakilagay sa markdown file

2024-08-20 17:51 UTC, Lanciee commented
na upload ko na po into markdown file si

2024-08-21 01:20 UTC, jtinosa approved these changes

2024-08-21 01:21 UTC, merged

2024-08-21 01:22 UTC, jtinosa commented
> na upload ko na po into markdown file sir

Nakalink pa rin sa google docs, Lagay nyo yung mismong story sa markdown